import type { Metadata } from 'next'
import './globals.css'
import { QueryProvider } from '@/providers/QueryProvider'
import { Header } from '@/components/common'


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<QueryProvider>
				<body suppressHydrationWarning={true}>
					<Header />
					<main className="lg:px-10 ">{children}</main>
				</body>
			</QueryProvider>
		</html>
	)
}
